_target_: data.stereo_dataset.StereoDataset
root_dir: /jobs/ADGRE/eguo/TEST/Stereo/Datasets/MPI-Sintel/Stereo/training
left_pattern: "final_left/**/*.png"
shot_pattern: "final_left/(.*)/"
frame_pattern: "_([0-9]*).png"
occlusion_format_str: "/jobs/ADGRE/elwa/OUT/Stereo/MPI-Sintel/training/unimatch_occlusion/{file_name}"
splat_format_str: "/jobs/ADGRE/elwa/OUT/Stereo/MPI-Sintel/training/unimatch_splat/{file_name}"
disp_format_str: "/jobs/ADGRE/elwa/OUT/Stereo/MPI-Sintel/training/unimatch_disparity/{file_name}"